CREATE DATABASE IF NOT EXISTS PDG DEFAULT CHARACTER SET utf8;
SET NAMES 'utf8';
USE PDG;

CREATE TABLE USER (
    username VARCHAR(128) NOT NULL COMMENT '用户名',
    epassword VARCHAR(256) NOT NULL COMMENT '加密后的密码',
    PRIMARY KEY (username)
) ENGINE = INNODB;

INSERT INTO USER(username, epassword) values('ADMIN', '21232f297a57a5a743894a0e4a801fc3');

CREATE TABLE TOKEN (
    token VARCHAR(128) NOT NULL COMMENT 'token',
    username VARCHAR(128) NOT NULL COMMENT '用户名',
    expireTime DATETIME NOT NULL COMMENT '过期时间',
    PRIMARY KEY (token)
) ENGINE = INNODB;